### ISSUE TITLE
The PinFi tool encounters an error on Pin version 3.30.

### ISSUE THREAD

**Issue by orhangunes** [DependableSystemsLab/pinfi#6]
When I follow the commands written in the Readme file and compile the PinFi tools, I encounter the following error. I downloaded Pin version 3.30 from the Intel website. These errors seem to be related to the Pin version. Does PinFi tools only work on Pin version 2.11? The oldest Pin version on the Intel website appears to be 3.13. I would appreciate your comment. Thank you.

_**/usr/include/x86_64-linux-gnu/c++/11/bits/os_defines.h:65:20: error: missing binary operator before token "("
   65 | # if __GLIBC_PREREQ(2, 34)
      |                    ^
In file included from /home/orhan/Desktop/PINFI/pin-3.30-gcc-linux/extras/cxx/include/fenv.h:59,
                 from /home/orhan/Desktop/PINFI/pin-3.30-gcc-linux/extras/cxx/include/cfenv:56,
                 from /usr/include/x86_64-linux-gnu/c++/11/bits/stdc++.h:55,
                 from instselector.cpp:9:
/home/orhan/Desktop/PINFI/pin-3.30-gcc-linux/extras/crt/include/fenv.h:47:21: error: ‘fexcept_t’ was not declared in this scope
   47 | int fegetexceptflag(fexcept_t *, int);
      |                     ^~~~~~~~~**_
